# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-17 20:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_author_post_rating_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='thumbnail',
            field=models.CharField(default=datetime.datetime(2016, 9, 17, 20, 43, 0, 900487, tzinfo=utc), max_length=60),
            preserve_default=False,
        ),
    ]
