# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-29 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20160918_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='post',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='tagassociations',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipes',
            name='authors',
            field=models.ManyToManyField(to='recipes.Author'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='post',
            field=models.OneToOneField(default='recipe', on_delete=django.db.models.deletion.CASCADE, to='recipes.Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipes',
            name='ratings',
            field=models.ManyToManyField(to='recipes.Rating'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(to='recipes.TagAssociations'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='videos',
            field=models.ManyToManyField(to='recipes.Videos'),
        ),
    ]
