# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-29 04:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20160929_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='post',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='ratings',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='videos',
        ),
        migrations.AddField(
            model_name='author',
            name='recipe',
            field=models.ForeignKey(default=datetime.datetime(2016, 9, 29, 4, 17, 23, 478915, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='recipe',
            field=models.ForeignKey(default=datetime.datetime(2016, 9, 29, 4, 17, 29, 798688, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='recipe',
            field=models.ForeignKey(default=datetime.datetime(2016, 9, 29, 4, 17, 34, 350421, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagassociations',
            name='recipe',
            field=models.ForeignKey(default=datetime.datetime(2016, 9, 29, 4, 17, 37, 86170, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videos',
            name='recipe',
            field=models.ForeignKey(default=datetime.datetime(2016, 9, 29, 4, 17, 39, 13752, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipes'),
            preserve_default=False,
        ),
    ]
