# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-17 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
